### ISSUE TITLE
Input the mneomonic of an ETH address, i already am using

### ISSUE THREAD

**Issue by seichris** [trustlines-network/mobileapp#25]
A user may have one ethereum address which is like his physical wallet. Not much cash, but always on hand - For receiving small donations, doing small payments, ERC20 Cash, signing stuff, etc.

As this user i would just remember the mneomonic to this address, so i got my wallet with a little money to survive always in my head. If i forget it, no problem. Not much money.

So in the app i would like to input my mnemonic and use my eth address, so i don't have to remember another password and i can use the ETH directly.

Good examples: myetherwallet, imToken

**Comment by Kispus** [comment]
How is this different from #19 ?

**Comment by Kispus** [comment]
Layout suggestion:

![Uploading Screen Shot 2017-08-14 at 4.05.38 PM.png…]()
