### ISSUE TITLE
Username in Header

### ISSUE THREAD

**Issue by jensneuber** [trustlines-network/mobileapp#28]
I would suggest, not to put the username in the header. Space is very limited and usernames usually do not fit in there, esp. if prefix with identicon

**Comment by Kispus** [comment]
I think this is a valid concern, which is also connected to the design elements of:

1) Having the settings tab and my account tab be separated

2) Placing the ' (+) action bar before in the right corner of top or bottom

3) Keeping the 'My profile' and 'settings' as two different pages

I will seek to come up with mock-ups of these options tomorrow

**Comment by Kispus** [comment]
Agreed upon this in previous UI-session.
