### ISSUE TITLE
Unable to change contact names or update personal account name

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/mobileapp#37]
1. my updated name does not change for my contacts (for example Kris -> Kristoffer)
2. Cannot change names of existing contacts (for example Chris -> Alice)

**Comment by jensneuber** [comment]
1. you mean on your contacts phone?
2. will come very soon :)

**Comment by jensneuber** [comment]
1. You can not change YOUR name on someone else's phone
2. Implemented
