### ISSUE TITLE
Confirm/sign payment

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#4]
User should see an overview of payment before confirming and signing the transaction.

- [x] back button
- [x] amount of payment (editable?)
- [x] subject of payment (editable?)
- [x] visualization of payment
- [x] transaction fees
- [x] button/slider to confirm/sign

![1-send - contact with tl - confirm](https://user-images.githubusercontent.com/17645687/27434903-99ace610-575a-11e7-8988-e8ea00d0872a.png)

**Comment by jensneuber** [comment]
Done
