### ISSUE TITLE
Bottom Navigation

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#40]
### Problem
Top navigation bar is more difficult to reach and take too much room on the upper half of the screen.

### Solution
Use bottom navigation bar instead. This design pattern is also part of the Google Material Design (https://material.io/guidelines/components/bottom-navigation.html) and has always been part of iOS design pattern.

Navigation items should be still the same + Scanner

![bottom-nav](https://user-images.githubusercontent.com/17645687/32950922-64b9e792-cba8-11e7-9be1-139721bfb0ee.png)

**Comment by Kispus** [comment]
How much an effort is this @jensneuber ? Unless it is very minimal, I would wait with this, I mean we already have a working navigation bar, could we not just leave it as it is for now and work on the unfinished screens?

**Comment by jensneuber** [comment]
Since we are going to show the menu bar only on the exact same screen, only at the bottom, the effort should be low

**Comment by dakingha69** [comment]
@jensneuber According to design guidelines the user should not be able to switch between tabs by swiping. See [here](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-behavior)

Regarding icons: The icons used in the mockups are the ones provided by the program, thats why I used them. But I don't really like them though... I would like to use [feather-icons](https://github.com/feathericons/feather). They are way cleaner and crisp IMO.

**Comment by jensneuber** [comment]
done
