### ISSUE TITLE
Change globe icon to trustlines in currency network sidenav

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#42]
### Problem
The "Globe" icon used for currency networks is not appropiate

### Solution
Use trustlines logo instead

![sidenav](https://user-images.githubusercontent.com/17645687/32951479-5dff2ae6-cbaa-11e7-83d8-925d3d7ee736.png)

**Comment by jensneuber** [comment]
We should get / create a simplified version ( less paths ) for smaller appearances

**Comment by jensneuber** [comment]
done
