### ISSUE TITLE
Main navigation bar

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/mobileapp#5]
We should decide on how our main navigation bar should look like.
- Home | Contacts | My Account
OR
- Home | Contact | Apps

In the second variant **Apps** would contain applications like **ETH Market**, **Cheques**, **Cross Currency Payments**.

And also maybe consider having a bottom navigation instead of top? Like

![1-home](https://user-images.githubusercontent.com/17645687/27435575-e788459e-575c-11e7-8846-c5c56ceb02dd.png)

**Comment by Kispus** [comment]
I would suggest to combine the two suggestions you have, move the action bar to the right corner and change the username to 'location specific' (as suggested in #28 ) 

This would look something like this:

![screen shot 2017-08-14 at 1 11 41 pm](https://user-images.githubusercontent.com/18598519/29269556-6e9d4a02-80f2-11e7-8a96-ab54dfb80a6e.png)

**Comment by Kispus** [comment]
Accoridng to the decision on the last UI-session, we are sticking with the current design (main navigation top, action button right corner) + removing Apps page.
